.PHONY: all all-windows

all: config-2x3.h config-2x3.h config-digi.h digipassikuva.c passikuva-2x2.c passikuva-2x3.c passikuva.c passikuva-digi.c passikuva.h
	gimptool-2.0 --install passikuva-digi.c
	gimptool-2.0 --install passikuva-2x2.c
	gimptool-2.0 --install passikuva-2x3.c

all-windows: .libs/passikuva-2x2.exe .libs/passikuva-2x3.exe .libs/passikuva-digi.exe

config-2x2.h:
	ln -s /home/hate/git/gimp-passikuva/config-2x2.h
config-2x3.h:
	ln -s /home/hate/git/gimp-passikuva/config-2x3.h
config-digi.h:
	ln -s /home/hate/git/gimp-passikuva/config-digi.h
passikuva-2x2.c:
	ln -s /home/hate/git/gimp-passikuva/passikuva-2x2.c
passikuva-2x3.c:
	ln -s /home/hate/git/gimp-passikuva/passikuva-2x3.c
passikuva-digi.c:
	ln -s /home/hate/git/gimp-passikuva/passikuva-digi.c
passikuva.h:
	ln -s /home/hate/git/gimp-passikuva/passikuva.h
passikuva.c:
	ln -s /home/hate/git/gimp-passikuva/passikuva.c
digipassikuva.c:
	ln -s /home/hate/git/gimp-passikuva/digipassikuva.c

.libs/passikuva-2x2.exe: config-2x2.h passikuva-2x2.c passikuva.c passikuva.h
	i686-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../.. -mms-bitfields -I/usr/i686-w64-mingw32/sys-root/mingw/include/gtk-2.0 -I/usr/i686-w64-mingw32/sys-root/mingw/lib/gtk-2.0/include -I/usr/i686-w64-mingw32/sys-root/mingw/include/atk-1.0 -I/usr/i686-w64-mingw32/sys-root/mingw/include/cairo -I/usr/i686-w64-mingw32/sys-root/mingw/include/gdk-pixbuf-2.0 -I/usr/i686-w64-mingw32/sys-root/mingw/include/pango-1.0 -I/usr/i686-w64-mingw32/sys-root/mingw/include/glib-2.0 -I/usr/i686-w64-mingw32/sys-root/mingw/lib/glib-2.0/include -I/usr/i686-w64-mingw32/sys-root/mingw/include/pixman-1 -I/usr/i686-w64-mingw32/sys-root/mingw/include/freetype2 -I/usr/i686-w64-mingw32/sys-root/mingw/include/libpng15 -I/usr/i686-w64-mingw32/sys-root/mingw/include/harfbuzz -DGIMP_DISABLE_DEPRECATED -DBABL_DISABLE_DEPRECATED -DGSEAL_ENABLE -DGDK_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATED -DGDK_MULTIHEAD_SAFE -DGTK_MULTIHEAD_SAFE  -I/usr/i686-w64-mingw32/sys-root/mingw/include -I${PREFIX}/include -Wall -Wdeclaration-after-statement -Wmissing-prototypes -Werror=missing-prototypes -Wstrict-prototypes -Wmissing-declarations -Winit-self -Wpointer-arith -Wold-style-definition -Wmissing-format-attribute -Wformat-security  -fno-common -fdiagnostics-show-option   -mms-bitfields -MT passikuva-2x2.o -MD -MP -MF .deps/passikuva-2x2.Tpo -c -o passikuva-2x2.o passikuva-2x2.c
	mv -f .deps/passikuva-2x2.Tpo .deps/passikuva-2x2.Po
	i686-w64-mingw32-windres --define ORIGINALFILENAME_STR="passikuva-2x2.exe" \
        --define INTERNALNAME_STR="passikuva-2x2" \
        --define TOP_SRCDIR="../.." \
        -I../../app \
        ../../build/windows/gimp-plug-ins.rc passikuva-2x2.rc.o
	/bin/sh ../../libtool  --tag=CC   --mode=link i686-w64-mingw32-gcc  -I/usr/i686-w64-mingw32/sys-root/mingw/include -I${PREFIX}/include -Wall -Wdeclaration-after-statement -Wmissing-prototypes -Werror=missing-prototypes -Wstrict-prototypes -Wmissing-declarations -Winit-self -Wpointer-arith -Wold-style-definition -Wmissing-format-attribute -Wformat-security  -fno-common -fdiagnostics-show-option   -mms-bitfields -mwindows -L/usr/i686-w64-mingw32/sys-root/mingw/lib -L${PREFIX}/lib -o passikuva-2x2.exe passikuva-2x2.o ../../libgimp/libgimpui-2.0.la ../../libgimpwidgets/libgimpwidgets-2.0.la ../../libgimpmodule/libgimpmodule-2.0.la ../../libgimp/libgimp-2.0.la ../../libgimpmath/libgimpmath-2.0.la  ../../libgimpconfig/libgimpconfig-2.0.la ../../libgimpcolor/libgimpcolor-2.0.la ../../libgimpbase/libgimpbase-2.0.la -Wl,-luuid -L/usr/i686-w64-mingw32/sys-root/mingw/lib -lgtk-win32-2.0 -lgdk-win32-2.0 -limm32 -lshell32 -lole32 -latk-1.0 -lpangocairo-1.0 -lgio-2.0 -lgdk_pixbuf-2.0 -lpangoft2-1.0 -lpangowin32-1.0 -lgdi32 -lfreetype -lfontconfig -lpango-1.0 -lm -lcairo -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lintl    -lintl  passikuva-2x2.rc.o
	i686-w64-mingw32-gcc -I/usr/i686-w64-mingw32/sys-root/mingw/include -I${PREFIX}/include -Wall -Wdeclaration-after-statement -Wmissing-prototypes -Werror=missing-prototypes -Wstrict-prototypes -Wmissing-declarations -Winit-self -Wpointer-arith -Wold-style-definition -Wmissing-format-attribute -Wformat-security -fno-common -fdiagnostics-show-option -mms-bitfields -mwindows -o .libs/passikuva-2x2.exe passikuva-2x2.o -Wl,-luuid passikuva-2x2.rc.o  -L/usr/i686-w64-mingw32/sys-root/mingw/lib -L${PREFIX}/lib ../../libgimp/.libs/libgimpui-2.0.dll.a ../../libgimp/.libs/libgimp-2.0.dll.a ../../libgimpwidgets/.libs/libgimpwidgets-2.0.dll.a ../../libgimpmodule/.libs/libgimpmodule-2.0.dll.a ../../libgimpwidgets/.libs/libgimpwidgets-2.0.dll.a ../../libgimpmodule/.libs/libgimpmodule-2.0.dll.a -lgmodule-2.0 ../../libgimp/.libs/libgimp-2.0.dll.a ../../libgimpconfig/.libs/libgimpconfig-2.0.dll.a ../../libgimpmath/.libs/libgimpmath-2.0.dll.a ../../libgimpconfig/.libs/libgimpconfig-2.0.dll.a ../../libgimpbase/.libs/libgimpbase-2.0.dll.a ../../libgimpcolor/.libs/libgimpcolor-2.0.dll.a ../../libgimpmath/.libs/libgimpmath-2.0.dll.a ../../libgimpcolor/.libs/libgimpcolor-2.0.dll.a ../../libgimpbase/.libs/libgimpbase-2.0.dll.a -lgtk-win32-2.0 -lgdk-win32-2.0 -limm32 -lshell32 -lole32 -latk-1.0 -lpangocairo-1.0 -lgio-2.0 -lgdk_pixbuf-2.0 -lpangoft2-1.0 -lpangowin32-1.0 -lgdi32 -lfreetype -lfontconfig -lpango-1.0 -lcairo -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lintl



.libs/passikuva-2x3.exe: config-2x3.h passikuva-2x3.c passikuva.c passikuva.h
	i686-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../.. -mms-bitfields -I/usr/i686-w64-mingw32/sys-root/mingw/include/gtk-2.0 -I/usr/i686-w64-mingw32/sys-root/mingw/lib/gtk-2.0/include -I/usr/i686-w64-mingw32/sys-root/mingw/include/atk-1.0 -I/usr/i686-w64-mingw32/sys-root/mingw/include/cairo -I/usr/i686-w64-mingw32/sys-root/mingw/include/gdk-pixbuf-2.0 -I/usr/i686-w64-mingw32/sys-root/mingw/include/pango-1.0 -I/usr/i686-w64-mingw32/sys-root/mingw/include/glib-2.0 -I/usr/i686-w64-mingw32/sys-root/mingw/lib/glib-2.0/include -I/usr/i686-w64-mingw32/sys-root/mingw/include/pixman-1 -I/usr/i686-w64-mingw32/sys-root/mingw/include/freetype2 -I/usr/i686-w64-mingw32/sys-root/mingw/include/libpng15 -I/usr/i686-w64-mingw32/sys-root/mingw/include/harfbuzz   -I${PREFIX}/include  -DGIMP_DISABLE_DEPRECATED -DBABL_DISABLE_DEPRECATED -DGSEAL_ENABLE -DGDK_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATED -DGDK_MULTIHEAD_SAFE -DGTK_MULTIHEAD_SAFE  -I/usr/i686-w64-mingw32/sys-root/mingw/include -Wall -Wdeclaration-after-statement -Wmissing-prototypes -Werror=missing-prototypes -Wstrict-prototypes -Wmissing-declarations -Winit-self -Wpointer-arith -Wold-style-definition -Wmissing-format-attribute -Wformat-security  -fno-common -fdiagnostics-show-option   -mms-bitfields -MT passikuva-2x3.o -MD -MP -MF .deps/passikuva-2x3.Tpo -c -o passikuva-2x3.o passikuva-2x3.c
	mv -f .deps/passikuva-2x3.Tpo .deps/passikuva-2x3.Po
	i686-w64-mingw32-windres --define ORIGINALFILENAME_STR="passikuva-2x3.exe" \
        --define INTERNALNAME_STR="passikuva-2x3" \
        --define TOP_SRCDIR="../.." \
        -I../../app \
        ../../build/windows/gimp-plug-ins.rc passikuva-2x3.rc.o
	/bin/sh ../../libtool  --tag=CC   --mode=link i686-w64-mingw32-gcc  -I/usr/i686-w64-mingw32/sys-root/mingw/include -I${PREFIX}/include -Wall -Wdeclaration-after-statement -Wmissing-prototypes -Werror=missing-prototypes -Wstrict-prototypes -Wmissing-declarations -Winit-self -Wpointer-arith -Wold-style-definition -Wmissing-format-attribute -Wformat-security  -fno-common -fdiagnostics-show-option   -mms-bitfields -mwindows -L/usr/i686-w64-mingw32/sys-root/mingw/lib -L${PREFIX}/lib -o passikuva-2x3.exe passikuva-2x3.o ../../libgimp/libgimpui-2.0.la ../../libgimpwidgets/libgimpwidgets-2.0.la ../../libgimpmodule/libgimpmodule-2.0.la ../../libgimp/libgimp-2.0.la ../../libgimpmath/libgimpmath-2.0.la  ../../libgimpconfig/libgimpconfig-2.0.la ../../libgimpcolor/libgimpcolor-2.0.la ../../libgimpbase/libgimpbase-2.0.la -Wl,-luuid -L/usr/i686-w64-mingw32/sys-root/mingw/lib -lgtk-win32-2.0 -lgdk-win32-2.0 -limm32 -lshell32 -lole32 -latk-1.0 -lpangocairo-1.0 -lgio-2.0 -lgdk_pixbuf-2.0 -lpangoft2-1.0 -lpangowin32-1.0 -lgdi32 -lfreetype -lfontconfig -lpango-1.0 -lm -lcairo -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lintl    -lintl  passikuva-2x3.rc.o
	i686-w64-mingw32-gcc -I/usr/i686-w64-mingw32/sys-root/mingw/include -I${PREFIX}/include -Wall -Wdeclaration-after-statement -Wmissing-prototypes -Werror=missing-prototypes -Wstrict-prototypes -Wmissing-declarations -Winit-self -Wpointer-arith -Wold-style-definition -Wmissing-format-attribute -Wformat-security -fno-common -fdiagnostics-show-option -mms-bitfields -mwindows -o .libs/passikuva-2x3.exe passikuva-2x3.o -Wl,-luuid passikuva-2x3.rc.o  -L/usr/i686-w64-mingw32/sys-root/mingw/lib -L${PREFIX}/lib ../../libgimp/.libs/libgimpui-2.0.dll.a ../../libgimp/.libs/libgimp-2.0.dll.a ../../libgimpwidgets/.libs/libgimpwidgets-2.0.dll.a ../../libgimpmodule/.libs/libgimpmodule-2.0.dll.a ../../libgimpwidgets/.libs/libgimpwidgets-2.0.dll.a ../../libgimpmodule/.libs/libgimpmodule-2.0.dll.a -lgmodule-2.0 ../../libgimp/.libs/libgimp-2.0.dll.a ../../libgimpconfig/.libs/libgimpconfig-2.0.dll.a ../../libgimpmath/.libs/libgimpmath-2.0.dll.a ../../libgimpconfig/.libs/libgimpconfig-2.0.dll.a ../../libgimpbase/.libs/libgimpbase-2.0.dll.a ../../libgimpcolor/.libs/libgimpcolor-2.0.dll.a ../../libgimpmath/.libs/libgimpmath-2.0.dll.a ../../libgimpcolor/.libs/libgimpcolor-2.0.dll.a ../../libgimpbase/.libs/libgimpbase-2.0.dll.a -lgtk-win32-2.0 -lgdk-win32-2.0 -limm32 -lshell32 -lole32 -latk-1.0 -lpangocairo-1.0 -lgio-2.0 -lgdk_pixbuf-2.0 -lpangoft2-1.0 -lpangowin32-1.0 -lgdi32 -lfreetype -lfontconfig -lpango-1.0 -lcairo -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lintl
.libs/passikuva-digi.exe: config-digi.h digipassikuva.c passikuva-digi.c passikuva.h
	i686-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../.. -mms-bitfields -I/usr/i686-w64-mingw32/sys-root/mingw/include/gtk-2.0 -I/usr/i686-w64-mingw32/sys-root/mingw/lib/gtk-2.0/include -I/usr/i686-w64-mingw32/sys-root/mingw/include/atk-1.0 -I/usr/i686-w64-mingw32/sys-root/mingw/include/cairo -I/usr/i686-w64-mingw32/sys-root/mingw/include/gdk-pixbuf-2.0 -I/usr/i686-w64-mingw32/sys-root/mingw/include/pango-1.0 -I/usr/i686-w64-mingw32/sys-root/mingw/include/glib-2.0 -I/usr/i686-w64-mingw32/sys-root/mingw/lib/glib-2.0/include -I/usr/i686-w64-mingw32/sys-root/mingw/include/pixman-1 -I/usr/i686-w64-mingw32/sys-root/mingw/include/freetype2 -I/usr/i686-w64-mingw32/sys-root/mingw/include/libpng15 -I/usr/i686-w64-mingw32/sys-root/mingw/include/harfbuzz   -I${PREFIX}/include  -DGIMP_DISABLE_DEPRECATED -DBABL_DISABLE_DEPRECATED -DGSEAL_ENABLE -DGDK_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATED -DGDK_MULTIHEAD_SAFE -DGTK_MULTIHEAD_SAFE  -I/usr/i686-w64-mingw32/sys-root/mingw/include -Wall -Wdeclaration-after-statement -Wmissing-prototypes -Werror=missing-prototypes -Wstrict-prototypes -Wmissing-declarations -Winit-self -Wpointer-arith -Wold-style-definition -Wmissing-format-attribute -Wformat-security  -fno-common -fdiagnostics-show-option   -mms-bitfields -MT passikuva-digi.o -MD -MP -MF .deps/passikuva-digi.Tpo -c -o passikuva-digi.o passikuva-digi.c
	mv -f .deps/passikuva-digi.Tpo .deps/passikuva-digi.Po
	i686-w64-mingw32-windres --define ORIGINALFILENAME_STR="passikuva-digi.exe" \
        --define INTERNALNAME_STR="passikuva-digi" \
        --define TOP_SRCDIR="../.." \
        -I../../app \
        ../../build/windows/gimp-plug-ins.rc passikuva-digi.rc.o
	/bin/sh ../../libtool  --tag=CC   --mode=link i686-w64-mingw32-gcc  -I/usr/i686-w64-mingw32/sys-root/mingw/include -I${PREFIX}/include -Wall -Wdeclaration-after-statement -Wmissing-prototypes -Werror=missing-prototypes -Wstrict-prototypes -Wmissing-declarations -Winit-self -Wpointer-arith -Wold-style-definition -Wmissing-format-attribute -Wformat-security  -fno-common -fdiagnostics-show-option   -mms-bitfields -mwindows -L/usr/i686-w64-mingw32/sys-root/mingw/lib -L${PREFIX}/lib -o passikuva-digi.exe passikuva-digi.o ../../libgimp/libgimpui-2.0.la ../../libgimpwidgets/libgimpwidgets-2.0.la ../../libgimpmodule/libgimpmodule-2.0.la ../../libgimp/libgimp-2.0.la ../../libgimpmath/libgimpmath-2.0.la  ../../libgimpconfig/libgimpconfig-2.0.la ../../libgimpcolor/libgimpcolor-2.0.la ../../libgimpbase/libgimpbase-2.0.la -Wl,-luuid -L/usr/i686-w64-mingw32/sys-root/mingw/lib -lgtk-win32-2.0 -lgdk-win32-2.0 -limm32 -lshell32 -lole32 -latk-1.0 -lpangocairo-1.0 -lgio-2.0 -lgdk_pixbuf-2.0 -lpangoft2-1.0 -lpangowin32-1.0 -lgdi32 -lfreetype -lfontconfig -lpango-1.0 -lm -lcairo -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lintl    -lintl  passikuva-digi.rc.o
	i686-w64-mingw32-gcc -I/usr/i686-w64-mingw32/sys-root/mingw/include -I${PREFIX}/include -Wall -Wdeclaration-after-statement -Wmissing-prototypes -Werror=missing-prototypes -Wstrict-prototypes -Wmissing-declarations -Winit-self -Wpointer-arith -Wold-style-definition -Wmissing-format-attribute -Wformat-security -fno-common -fdiagnostics-show-option -mms-bitfields -mwindows -o .libs/passikuva-digi.exe passikuva-digi.o -Wl,-luuid passikuva-digi.rc.o  -L/usr/i686-w64-mingw32/sys-root/mingw/lib -L${PREFIX}/lib ../../libgimp/.libs/libgimpui-2.0.dll.a ../../libgimp/.libs/libgimp-2.0.dll.a ../../libgimpwidgets/.libs/libgimpwidgets-2.0.dll.a ../../libgimpmodule/.libs/libgimpmodule-2.0.dll.a ../../libgimpwidgets/.libs/libgimpwidgets-2.0.dll.a ../../libgimpmodule/.libs/libgimpmodule-2.0.dll.a -lgmodule-2.0 ../../libgimp/.libs/libgimp-2.0.dll.a ../../libgimpconfig/.libs/libgimpconfig-2.0.dll.a ../../libgimpmath/.libs/libgimpmath-2.0.dll.a ../../libgimpconfig/.libs/libgimpconfig-2.0.dll.a ../../libgimpbase/.libs/libgimpbase-2.0.dll.a ../../libgimpcolor/.libs/libgimpcolor-2.0.dll.a ../../libgimpmath/.libs/libgimpmath-2.0.dll.a ../../libgimpcolor/.libs/libgimpcolor-2.0.dll.a ../../libgimpbase/.libs/libgimpbase-2.0.dll.a -lgtk-win32-2.0 -lgdk-win32-2.0 -limm32 -lshell32 -lole32 -latk-1.0 -lpangocairo-1.0 -lgio-2.0 -lgdk_pixbuf-2.0 -lpangoft2-1.0 -lpangowin32-1.0 -lgdi32 -lfreetype -lfontconfig -lpango-1.0 -lcairo -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lintl
